//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 11:56:08 AM ICT 
//


package tintt.difficulti_estimation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tintt.difficulti_estimation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModelEstimation_QNAME = new QName("http://www.titiisme.com/schema/estimation-for-model", "model-estimation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tintt.difficulti_estimation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModelEstimation }
     * 
     */
    public ModelEstimation createModelEstimation() {
        return new ModelEstimation();
    }

    /**
     * Create an instance of {@link DifficultyEstimation }
     * 
     */
    public DifficultyEstimation createDifficultyEstimation() {
        return new DifficultyEstimation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelEstimation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.titiisme.com/schema/estimation-for-model", name = "model-estimation")
    public JAXBElement<ModelEstimation> createModelEstimation(ModelEstimation value) {
        return new JAXBElement<ModelEstimation>(_ModelEstimation_QNAME, ModelEstimation.class, null, value);
    }

}
